format_code_in_doc_comments = true
format_macro_matchers = true
format_macro_bodies = true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
reorder_impl_items = true
unstable_features = true
version = "Two"
wrap_comments = true
